sudo: required
services:
 - docker

before_install:
  - docker build -t leedbates/frontend-dockerize -f Dockerfile.dev . 

script:
  - docker run leedbates/frontend-dockerize npm run test -- --coverage